- src/functionalTest/java/uk/gov/hmcts/reform/hmc/jp/controllers/SampleFunctionalTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/jp/config/SwaggerPublisherTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/jp/controllers/GetWelcomeTest.java
- src/main/java/uk/gov/hmcts/reform/hmc/jp/Application.java
- src/main/java/uk/gov/hmcts/reform/hmc/jp/config/OpenAPIConfiguration.java
- src/main/java/uk/gov/hmcts/reform/hmc/jp/controllers/RootController.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmc/jp/controllers/SampleSmokeTest.java
https://tools.hmcts.net/jira/browse/IJPS-1
The repository must have skeleton structure in place for the directory structure 
```
[ ] Yes
[x] No
```
> Changed SRC directories

- gradle/wrapper/gradle-wrapper.properties
Reverts hmcts/hmc-judicial-payment-service#10
> Revert "Update dependency gradle to v8.0.1"

- src/integrationTest/java/uk/gov/hmcts/reform/jps/repository/SittingRecordRepositoryTest.java
https://tools.hmcts.net/jira/browse/IJPS-48
to trigger build
```
[ ] Yes
[ x] No
```
> IJPS-48: Removed extra line

- charts/jps-judicial-payment-service/Chart.yaml
- charts/jps-judicial-payment-service/values.yaml
- src/functionalTest/resources/test-config.properties
- src/main/resources/application.yaml
> Update frontend service name

- Jenkinsfile_CNP
- charts/jps-judicial-payment-service/Chart.yaml
- charts/jps-judicial-payment-service/values.yaml
- config/owasp/suppressions.xml
- src/cftlib/java/uk/gov/hmcts/reform/jps/CftLibConfig.java
https://tools.hmcts.net/jira/browse/IJPS-88
This adds the new user and role to the cftlib config and also the secrets for the FTS
.
```
[ ] Yes
[X] No
```
> IJPS-88 Adding  jps-JOH-admin role and user

- src/integrationTest/java/uk/gov/hmcts/reform/jps/repository/CourtVenueRepositoryTest.java
- src/main/java/uk/gov/hmcts/reform/jps/domain/CourtVenue.java
- src/main/java/uk/gov/hmcts/reform/jps/repository/CourtVenueRepository.java
- src/main/resources/db/migration/V20230727_64__IJPS-64_courtVenue.sql
https://tools.hmcts.net/jira/browse/IJPS-64
A new Database table - court_venue
```
[ ] Yes
[X ] No
```
> IJPS-64: new Database table - court_venue

- Jenkinsfile_CNP
- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/jps/StepDefinitions.java
- src/functionalTest/java/uk/gov/hmcts/reform/jps/config/Endpoints.java
- src/functionalTest/java/uk/gov/hmcts/reform/jps/config/TestVariables.java
- src/functionalTest/java/uk/gov/hmcts/reform/jps/testutils/PropertiesReader.java
- src/functionalTest/resources/features/F-003 - Delete sittingRecords endpoint/F-003.feature
- src/functionalTest/resources/features/F-004 - Post sittingRecords endpoint/F-004.feature
- src/functionalTest/resources/features/F-005 - Post searchSittingRecords endpoint/F-005.feature
- src/functionalTest/resources/payloads/F-003_CreateRecord.json
- src/functionalTest/resources/payloads/F-005_allFields.json
- src/functionalTest/resources/test-config.properties
> IJPS-53 Functional tests for the DELETE /sittingRecords endpoint

- config/owasp/suppressions.xml
- src/functionalTest/resources/features/F-006 - Post submitSittingRecords endpoint/F-006.feature
- src/functionalTest/resources/payloads/F-006_generic.json
- src/functionalTest/resources/payloads/S-004.2.json
- src/functionalTest/resources/payloads/S-006.12_createRecord.json
- src/functionalTest/resources/payloads/S-006.13_createRecords.json
- src/functionalTest/resources/payloads/S-006.14_createRecord.json
- src/functionalTest/resources/payloads/S-006.15_createRecord.json
- src/functionalTest/resources/payloads/S-006.16_createRecord.json
- src/functionalTest/resources/payloads/S-006.17_createRecord.json
> FTs for IJPS-77

- src/functionalTest/resources/features/F-004 - Post recordSittingRecords endpoint/F-004.feature
- src/functionalTest/resources/payloads/S-004.29.json
- src/functionalTest/resources/payloads/S-004.30.json
- src/functionalTest/resources/payloads/S-004.31.json
- src/functionalTest/resources/payloads/S-004.32.json
- src/functionalTest/resources/payloads/S-004.33.json
- src/functionalTest/resources/payloads/S-004.34.json
- src/functionalTest/resources/payloads/S-004.35.json
https://tools.hmcts.net/jira/browse/IJPS-104
Functional test scenarios for potential duplicates when epimmsId is different.
```
[ ] Yes
[X] No
```
> IJPS-104 Functional tests

- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/jps/StepDefinitions.java
- src/functionalTest/resources/features/F-006 - Post submitSittingRecords endpoint/F-006.feature
- src/functionalTest/resources/payloads/setup/addJOHs.json
> IJPS-108_FT

- src/functionalTest/java/uk/gov/hmcts/reform/jps/StepDefinitions.java
- src/functionalTest/resources/features/F-004 - Post recordSittingRecords endpoint/F-004.feature
- src/functionalTest/resources/features/F-005 - Post searchSittingRecords endpoint/F-005.feature
- src/functionalTest/resources/features/F-006 - Post submitSittingRecords endpoint/F-006.feature
- src/functionalTest/resources/payloads/setup/addServices.json
https://tools.hmcts.net/jira/browse/IJPS-105
Update validation of hmctsServiceCode
```
[ ] Yes
[ x ] No
```
> Ijps 105 ft v2

- .github/renovate.json
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/jps/BaseTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/jps/controllers/RecordSittingRecordsControllerITest.java
- src/integrationTest/java/uk/gov/hmcts/reform/jps/controllers/SittingRecordControllerITest.java
- src/integrationTest/java/uk/gov/hmcts/reform/jps/controllers/SubmitSittingRecordsControllerITest.java
- src/integrationTest/java/uk/gov/hmcts/reform/jps/repository/ServiceRepositoryTest.java
- src/integrationTest/resources/sql/add_sitting_record_status_history.sql
- src/integrationTest/resources/sql/insert_service_test_data.sql
- src/integrationTest/resources/sql/reset_database.sql
- src/main/java/uk/gov/hmcts/reform/jps/controllers/RecordSittingRecordsController.java
- src/main/java/uk/gov/hmcts/reform/jps/controllers/SittingRecordController.java
- src/main/java/uk/gov/hmcts/reform/jps/controllers/SubmitSittingRecordsController.java
- src/main/java/uk/gov/hmcts/reform/jps/controllers/util/Utility.java
- src/main/java/uk/gov/hmcts/reform/jps/repository/ServiceRepository.java
- src/main/java/uk/gov/hmcts/reform/jps/services/ServiceService.java
- src/test/java/uk/gov/hmcts/reform/jps/controllers/RecordSittingRecordsControllerTest.java
- src/test/java/uk/gov/hmcts/reform/jps/controllers/SittingRecordControllerTest.java
- src/test/java/uk/gov/hmcts/reform/jps/controllers/SubmitSittingRecordsControllerTest.java
- src/test/java/uk/gov/hmcts/reform/jps/controllers/util/UtilityTest.java
- src/test/java/uk/gov/hmcts/reform/jps/repository/SittingRecordRepositorySearchImplTest.java
- src/test/java/uk/gov/hmcts/reform/jps/services/ServiceServiceTest.java
https://tools.hmcts.net/jira/browse/IJPS-105
Update validation of hmctsServiceCode
```
[ ] Yes
[ x] No
```
> IJPS-105: Update validation of hmctsServiceCode

- src/integrationTest/java/uk/gov/hmcts/reform/jps/repository/ExportedFileDataHeaderRepositoryTest.java
- src/integrationTest/resources/sql/reset_database.sql
- src/main/java/uk/gov/hmcts/reform/jps/domain/ExportedFileDataHeader.java
- src/main/java/uk/gov/hmcts/reform/jps/repository/ExportedFileDataHeaderRepository.java
- src/main/resources/db/migration/V20230927_112__IJPS-112_exportedFileDataHeader.sql
https://tools.hmcts.net/jira/browse/IJPS-112
Create a new Database table - exported_file_data_header
```
[ ] Yes
[ X] No
```
> IJPS-112: Create a new Database table - exported_file_data_header

- src/integrationTest/java/uk/gov/hmcts/reform/jps/repository/ExportedFileDataHeaderRepositoryTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/jps/repository/ExportedFilesRepositoryTest.java
- src/main/java/uk/gov/hmcts/reform/jps/domain/ExportedFile.java
- src/main/java/uk/gov/hmcts/reform/jps/domain/ExportedFileDataHeader.java
- src/main/java/uk/gov/hmcts/reform/jps/repository/ExportedFilesRepository.java
- src/main/resources/db/migration/V20230927_113__IJPS-113_exportedFiles.sql
https://tools.hmcts.net/jira/browse/IJPS-113
Create a new Database table - exported_files
```
[ ] Yes
[ x] No
```
> IJPS-113: Create a new Database table - exported_files

- src/integrationTest/java/uk/gov/hmcts/reform/jps/repository/ExportedFileDataHeaderRepositoryTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/jps/repository/ExportedFileDataRepositoryTest.java
- src/integrationTest/resources/sql/reset_database.sql
- src/main/java/uk/gov/hmcts/reform/jps/domain/ExportedFile.java
- src/main/java/uk/gov/hmcts/reform/jps/domain/ExportedFileData.java
- src/main/java/uk/gov/hmcts/reform/jps/repository/ExportedFileDataRepository.java
- src/main/resources/db/migration/V20230929_114__IJPS-114_exportedFileData.sql
https://tools.hmcts.net/jira/browse/IJPS-114
Create a new Database table - exported_file_data
```
[ ] Yes
[ x] No
```
> IJPS-114: Create a new Database table - exported_file_data

- src/integrationTest/java/uk/gov/hmcts/reform/jps/repository/SittingDaysRepositoryTest.java
- src/integrationTest/resources/sql/reset_database.sql
- src/main/java/uk/gov/hmcts/reform/jps/domain/SittingDays.java
- src/main/java/uk/gov/hmcts/reform/jps/repository/SittingDaysRepository.java
- src/main/resources/db/migration/V20231004_118__IJPS-118_sitting_days.sql
https://tools.hmcts.net/jira/browse/IJPS-118
Create a new Database table - sitting_days
```
[ ] Yes
[x ] No
```
> IJPS-118: Create a new Database table - sitting_days

- src/integrationTest/java/uk/gov/hmcts/reform/jps/BaseTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/jps/repository/SittingDaysRepositoryTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/jps/repository/SittingRecordRepositoryTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/jps/services/SittingRecordServiceITest.java
- src/integrationTest/resources/sql/insert_published_test_data.sql
- src/main/java/uk/gov/hmcts/reform/jps/model/FinancialYearRecords.java
- src/main/java/uk/gov/hmcts/reform/jps/model/PublishSittingRecordCount.java
- src/main/java/uk/gov/hmcts/reform/jps/repository/SittingDaysRepository.java
- src/main/java/uk/gov/hmcts/reform/jps/repository/SittingRecordRepository.java
- src/main/java/uk/gov/hmcts/reform/jps/services/SittingDaysService.java
- src/main/java/uk/gov/hmcts/reform/jps/services/SittingRecordService.java
- src/test/java/uk/gov/hmcts/reform/jps/services/SittingDaysServiceTest.java
- src/test/java/uk/gov/hmcts/reform/jps/services/SittingRecordServiceTest.java
https://tools.hmcts.net/jira/browse/IJPS-117
Calculate Published sitting record count
```
[ ] Yes
[X ] No
```
> IJPS-117: Calculate Published sitting record count

- charts/jps-judicial-payment-service/Chart.yaml
- config/owasp/suppressions.xml
- src/functionalTest/resources/payloads/setup/addServices.json
> PR to fix FTs

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&view=detail&selectedIssue=CCD-5129
Switching old secret values to v15
```
[ ] Yes
[x] No
```
> Switching old secret values to v15

- infrastructure/main.tf
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-5129
Cleaning up V15 secrets, Retained old secret names but pointed to V15 module. 
```
[ ] Yes
[x] No
```
> Cleaning up V15 secrets

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-5129
Re-enabling demo branch sync with master as part of post postgres migration cleanup
```
[ ] Yes
[x] No
```
> Re-enabling demo branch sync to master

- src/functionalTest/resources/features/F-004 - Post recordSittingRecords endpoint/F-004.feature
- src/functionalTest/resources/features/F-006 - Post submitSittingRecords endpoint/F-006.feature
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-5129
Adding further ignore tags to failing functional tests in order to temporarily suppress 
```
[ ] Yes
[x] No
```
> Adding Ignore tags to further tests which fail

- charts/jps-judicial-payment-service/Chart.yaml
[Bumping charts.yaml ](https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-5129)
Bumping charts.yaml 
```
[ ] Yes
[x] No
```
> Bumping charts by one increment
